[2024-11-24T06:59:04.722+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T06:54:26.269966+00:00/task_id=train_model permission to 509
[2024-11-24T06:59:04.722+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T06:54:26.269966+00:00/task_id=train_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T06:54:26.269966+00:00/task_id=train_model'
[2024-11-24T06:59:04.748+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T06:54:26.269966+00:00/task_id=train_model permission to 509
[2024-11-24T06:59:04.749+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T06:54:26.269966+00:00/task_id=train_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T06:54:26.269966+00:00/task_id=train_model'
[2024-11-24T06:59:04.775+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_pipeline.train_model manual__2024-11-24T06:54:26.269966+00:00 [queued]>
[2024-11-24T06:59:04.782+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_pipeline.train_model manual__2024-11-24T06:54:26.269966+00:00 [queued]>
[2024-11-24T06:59:04.783+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-11-24T06:59:04.796+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): train_model> on 2024-11-24 06:54:26.269966+00:00
[2024-11-24T06:59:04.811+0000] {standard_task_runner.py:57} INFO - Started process 29817 to run task
[2024-11-24T06:59:04.813+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'model_training_pipeline', 'train_model', 'manual__2024-11-24T06:54:26.269966+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/model_training_pipeline_dag/model_training_dag.py', '--cfg-path', '/tmp/tmp1v4i8bew']
[2024-11-24T06:59:04.816+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask train_model
[2024-11-24T06:59:04.868+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T06:54:26.269966+00:00/task_id=train_model permission to 509
[2024-11-24T06:59:04.869+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T06:54:26.269966+00:00/task_id=train_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T06:54:26.269966+00:00/task_id=train_model'
[2024-11-24T06:59:04.870+0000] {task_command.py:415} INFO - Running <TaskInstance: model_training_pipeline.train_model manual__2024-11-24T06:54:26.269966+00:00 [running]> on host 71596b931411
[2024-11-24T06:59:04.952+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_training_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T06:54:26.269966+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T06:54:26.269966+00:00'
[2024-11-24T07:21:25.313+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-11-24T07:21:25.317+0000] {process_utils.py:131} INFO - Sending 15 to group 29817. PIDs of all processes in the group: [29817]
[2024-11-24T07:21:25.317+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 29817
[2024-11-24T07:21:25.318+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-24T07:21:25.410+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=29817, status='terminated', exitcode=0, started='06:59:04') (29817) terminated with exit code 0
