[2024-11-18T10:38:25.718+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=weather_variables_feature_engineering permission to 509
[2024-11-18T10:38:25.719+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=weather_variables_feature_engineering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=weather_variables_feature_engineering'
[2024-11-18T10:38:25.745+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=weather_variables_feature_engineering permission to 509
[2024-11-18T10:38:25.746+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=weather_variables_feature_engineering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=weather_variables_feature_engineering'
[2024-11-18T10:38:25.767+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_pipeline.weather_variables_feature_engineering manual__2024-11-18T10:28:51.600561+00:00 [queued]>
[2024-11-18T10:38:25.774+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_pipeline.weather_variables_feature_engineering manual__2024-11-18T10:28:51.600561+00:00 [queued]>
[2024-11-18T10:38:25.774+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-11-18T10:38:25.786+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): weather_variables_feature_engineering> on 2024-11-18 10:28:51.600561+00:00
[2024-11-18T10:38:25.798+0000] {standard_task_runner.py:57} INFO - Started process 26481 to run task
[2024-11-18T10:38:25.801+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'model_training_pipeline', 'weather_variables_feature_engineering', 'manual__2024-11-18T10:28:51.600561+00:00', '--job-id', '316', '--raw', '--subdir', 'DAGS_FOLDER/model_training_pipeline_dag/model_training_dag.py', '--cfg-path', '/tmp/tmpqi1dd1am']
[2024-11-18T10:38:25.804+0000] {standard_task_runner.py:85} INFO - Job 316: Subtask weather_variables_feature_engineering
[2024-11-18T10:38:25.845+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=weather_variables_feature_engineering permission to 509
[2024-11-18T10:38:25.845+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=weather_variables_feature_engineering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=weather_variables_feature_engineering'
[2024-11-18T10:38:25.847+0000] {task_command.py:415} INFO - Running <TaskInstance: model_training_pipeline.weather_variables_feature_engineering manual__2024-11-18T10:28:51.600561+00:00 [running]> on host 16801ac1f6e4
[2024-11-18T10:38:25.917+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_training_pipeline' AIRFLOW_CTX_TASK_ID='weather_variables_feature_engineering' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T10:28:51.600561+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T10:28:51.600561+00:00'
[2024-11-18T10:47:33.645+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-11-18T10:47:33.657+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=model_training_pipeline, task_id=weather_variables_feature_engineering, execution_date=20241118T102851, start_date=20241118T103825, end_date=20241118T104733
[2024-11-18T10:47:33.743+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-18T10:47:33.772+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
