[2024-11-24T04:56:00.590+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T04:51:44.686477+00:00/task_id=train_model permission to 509
[2024-11-24T04:56:00.591+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T04:51:44.686477+00:00/task_id=train_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T04:51:44.686477+00:00/task_id=train_model'
[2024-11-24T04:56:00.623+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T04:51:44.686477+00:00/task_id=train_model permission to 509
[2024-11-24T04:56:00.624+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T04:51:44.686477+00:00/task_id=train_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T04:51:44.686477+00:00/task_id=train_model'
[2024-11-24T04:56:00.653+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_pipeline.train_model manual__2024-11-24T04:51:44.686477+00:00 [queued]>
[2024-11-24T04:56:00.663+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_pipeline.train_model manual__2024-11-24T04:51:44.686477+00:00 [queued]>
[2024-11-24T04:56:00.663+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-11-24T04:56:00.680+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): train_model> on 2024-11-24 04:51:44.686477+00:00
[2024-11-24T04:56:00.692+0000] {standard_task_runner.py:57} INFO - Started process 4742 to run task
[2024-11-24T04:56:00.695+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'model_training_pipeline', 'train_model', 'manual__2024-11-24T04:51:44.686477+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/model_training_pipeline_dag/model_training_dag.py', '--cfg-path', '/tmp/tmphlienuhk']
[2024-11-24T04:56:00.699+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask train_model
[2024-11-24T04:56:00.750+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T04:51:44.686477+00:00/task_id=train_model permission to 509
[2024-11-24T04:56:00.751+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T04:51:44.686477+00:00/task_id=train_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-24T04:51:44.686477+00:00/task_id=train_model'
[2024-11-24T04:56:00.752+0000] {task_command.py:415} INFO - Running <TaskInstance: model_training_pipeline.train_model manual__2024-11-24T04:51:44.686477+00:00 [running]> on host 71596b931411
[2024-11-24T04:56:00.842+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_training_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T04:51:44.686477+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T04:51:44.686477+00:00'
[2024-11-24T04:59:06.088+0000] {logging_mixin.py:151} INFO - Data has been normalised
[2024-11-24T04:59:18.845+0000] {logging_mixin.py:151} INFO - Sequences have been saved to /opt/***/sequences/x_sequences_train_7day.npy and /opt/***/sequences/y_sequences_train_7day.npy
[2024-11-24T04:59:30.139+0000] {logging_mixin.py:151} INFO - Sequences have been saved to /opt/***/sequences/x_sequences_train_14day.npy and /opt/***/sequences/y_sequences_train_14day.npy
[2024-11-24T04:59:41.964+0000] {logging_mixin.py:151} INFO - Sequences have been saved to /opt/***/sequences/x_sequences_train_30day.npy and /opt/***/sequences/y_sequences_train_30day.npy
[2024-11-24T05:00:45.879+0000] {local_task_job_runner.py:228} INFO - Task exited with return code -9
[2024-11-24T05:00:45.909+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
