[2024-11-18T11:07:31.803+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=test_data_creation permission to 509
[2024-11-18T11:07:31.804+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=test_data_creation permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=test_data_creation'
[2024-11-18T11:07:31.833+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=test_data_creation permission to 509
[2024-11-18T11:07:31.834+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=test_data_creation permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=test_data_creation'
[2024-11-18T11:07:31.857+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_pipeline.test_data_creation manual__2024-11-18T10:28:51.600561+00:00 [queued]>
[2024-11-18T11:07:31.866+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_pipeline.test_data_creation manual__2024-11-18T10:28:51.600561+00:00 [queued]>
[2024-11-18T11:07:31.866+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-11-18T11:07:31.879+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): test_data_creation> on 2024-11-18 10:28:51.600561+00:00
[2024-11-18T11:07:31.892+0000] {standard_task_runner.py:57} INFO - Started process 32348 to run task
[2024-11-18T11:07:31.895+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'model_training_pipeline', 'test_data_creation', 'manual__2024-11-18T10:28:51.600561+00:00', '--job-id', '319', '--raw', '--subdir', 'DAGS_FOLDER/model_training_pipeline_dag/model_training_dag.py', '--cfg-path', '/tmp/tmp1cjtuyqq']
[2024-11-18T11:07:31.897+0000] {standard_task_runner.py:85} INFO - Job 319: Subtask test_data_creation
[2024-11-18T11:07:31.941+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=test_data_creation permission to 509
[2024-11-18T11:07:31.942+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=test_data_creation permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-18T10:28:51.600561+00:00/task_id=test_data_creation'
[2024-11-18T11:07:31.943+0000] {task_command.py:415} INFO - Running <TaskInstance: model_training_pipeline.test_data_creation manual__2024-11-18T10:28:51.600561+00:00 [running]> on host 16801ac1f6e4
[2024-11-18T11:07:32.018+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_training_pipeline' AIRFLOW_CTX_TASK_ID='test_data_creation' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T10:28:51.600561+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T10:28:51.600561+00:00'
[2024-11-18T11:12:02.955+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-11-18T11:12:02.967+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=model_training_pipeline, task_id=test_data_creation, execution_date=20241118T102851, start_date=20241118T110731, end_date=20241118T111202
[2024-11-18T11:12:03.015+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-18T11:12:03.036+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
